Initial version of validation PR (m4l4).
otuskotlin/202212-ok-marketplace pull request #25
Opened 2023-04-08 15:58 UTC by tano

@svok 
Я не стал включать библиотеку konform, самописную библиотеку валидации и неиспользуемый пример с маперами, кажется, это достаточно упомянуть в презентации. Если будут возражения, могу включить.

2023-04-09 01:53 UTC, svok requested changes

2023-04-09 01:53 UTC, svok commented on ok-marketplace-app-ktor/src/commonMain/kotlin/Application.kt
> +            v2Offer(processor = processor, appSettings = appSettings)
Есть общий класс настроек приложения. Создан как раз для того, чтоб избежать миллиона аргументов. Все дополнительные компоненты должны передаваться через него.

2023-04-09 01:53 UTC, svok commented on ok-marketplace-app-ktor/src/commonMain/kotlin/v2/AdController.kt
> +suspend fun ApplicationCall.createAd(processor: MkplAdProcessor, logger: IMpLogWrapper) =
Отмени это и верни старую нотацию.

2023-04-09 01:53 UTC, svok commented on ok-marketplace-app-ktor/src/commonMain/kotlin/v2/rest.kt
> +            call.offersAd(processor, loggerOffers)
Нужно вернуть нотацию с настройками

2023-04-09 01:53 UTC, svok commented on ok-marketplace-app-ktor/src/jvmMain/kotlin/ApplicationJvm.kt
>          route("v1") {
Вот здесь ты сломал сваггер

2023-04-09 01:53 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/controllers/v2/ControllerHelperV2.kt
> +        command?.also { ctx.command = it }
Это тоже в лог обёртку только идентификато со словом failure

2023-04-09 01:53 UTC, svok commented on ok-marketplace-biz/src/commonMain/kotlin/ru/otus/otuskotlin/marketplace/biz/validation/ValidateIdProperFormat.kt
> +            description = "value $encodedId must contain only"
Что "только"?

2023-04-09 06:20 UTC, tano commented
Так, замечания поправил, но осталась еще проблема с логами: logback 1.4.6 конфликтует с тем, что тащит Spring Boot (1.2.11). Есть два варианта: поднимать мажорную версию бута или опускать logbackVersion.
@svok, как поступим?

2023-04-09 06:51 UTC, tano commented on ok-marketplace-app-ktor/src/commonMain/kotlin/v2/rest.kt
> +            call.offersAd(processor, loggerOffers)
Тут предлагаю компромисс: оставить два параметра, потому что логер с его классом определяем один раз и передаем во всё, что ниже. Ну а сюда пусть приходит appSettings, согласен.

2023-04-09 06:52 UTC, tano commented on ok-marketplace-app-ktor/src/commonMain/kotlin/v2/AdController.kt
> +suspend fun ApplicationCall.createAd(processor: MkplAdProcessor, logger: IMpLogWrapper) =
Тут предлагаю компромисс: оставить два параметра, потому что логер с его классом определяем один раз и передаем во всё, что ниже. Ну а сюда пусть приходит appSettings, согласен.

2023-04-09 06:52 UTC, tano commented on ok-marketplace-app-ktor/src/jvmMain/kotlin/ApplicationJvm.kt
>          route("v1") {
Ок убрал

2023-04-09 06:52 UTC, tano commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/controllers/v2/ControllerHelperV2.kt
> +        command?.also { ctx.command = it }
Done

2023-04-09 06:52 UTC, tano commented on ok-marketplace-biz/src/commonMain/kotlin/ru/otus/otuskotlin/marketplace/biz/validation/ValidateIdProperFormat.kt
> +            description = "value $encodedId must contain only"
Fixed

2023-04-10 19:16 UTC, svok requested changes

2023-04-10 19:16 UTC, svok commented on ok-marketplace-app-ktor/src/commonMain/kotlin/v2/AdController.kt
> +suspend fun ApplicationCall.createAd(processor: MkplAdProcessor, logger: IMpLogWrapper) =
Ничего не понимаю. Зачем тебе здесь 2 параметра? Просто передай appSettings, там есть и процессор, и логер и еще куча параметров, про которые ты сейчас не догадываешься, но они позарез нужны будут потом.

2023-04-10 19:16 UTC, svok commented on ok-marketplace-app-ktor/src/commonMain/kotlin/v2/ControllerHelperV2.kt
> +    logger: IMpLogWrapper,
Сколько параметров ты готов выдержать?
Если у нас потом будет 20 параметров, то это уже нужно подумать о классе или еще можно потерпеть?

2023-04-10 19:16 UTC, svok commented on ok-marketplace-app-ktor/src/commonMain/kotlin/v2/rest.kt
> +            call.offersAd(processor, loggerOffers)
Это не логер, если что. Это логер-провайдер. Он создает логеры.
В общем, здесь должен быть appSettings

2023-04-10 19:16 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/controllers/v1/ControllerHelperV1.kt
> +        logger.doWithLogging(id = "${logId}-failure") {
Не только здесь. В остальные хелперах тоже нужно обернуть

2023-04-10 19:16 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/controllers/v2/OfferControllerV2.kt
> +    private val loggerProvider: MpLoggerProvider,
Чем это лучше, чем просто прокинуть один appSettings

2023-04-11 05:21 UTC, tano commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/controllers/v1/ControllerHelperV1.kt
> +        logger.doWithLogging(id = "${logId}-failure") {
В хелперах везде добавил логирование.

2023-04-11 05:37 UTC, tano commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/controllers/v2/OfferControllerV2.kt
> +    private val loggerProvider: MpLoggerProvider,
Я думал так сделать, но здесь вот какой момент: у нас в OfferController приезжают зависимости processor и loggerProvider, они объявлены как бины, при этом loggerProvider мы используем по месту, получая оттуда logger для конкретного класса, если эти моменты выносить в appSettings, получается некоторый дополнительный слой, искусственный, как кажется.  Я боюсь, если мы его будем использовать вместо контекста DI, будет не очень хорошо с точки зрения читаемости кода в плане понимания реальных зависимостей классов друг от друга.

2023-04-11 05:45 UTC, tano commented on ok-marketplace-app-ktor/src/commonMain/kotlin/v2/ControllerHelperV2.kt
> +    logger: IMpLogWrapper,
OK, тут вернул appSettings для получения processor, logger мы на уровне этой функции не можем сами понять какой надо, поэтому оставил проброс сверху.

2023-04-11 20:17 UTC, svok approved these changes

2023-04-12 18:11 UTC, merged