M5L1: initial version.
otuskotlin/202212-ok-marketplace pull request #27
Opened 2023-04-22 20:27 UTC by tano

Прошу провести CR.

2023-04-23 15:34 UTC, svok requested changes

2023-04-23 15:34 UTC, svok commented on README.md
> +[//]: # (2. [ok-marketplace-repo-in-memory]&#40;ok-marketplace-repo-in-memory&#41; - Репозиторий на базе кэша в памяти для тестирования)
Можно раскомментировать

2023-04-23 15:34 UTC, svok commented on ok-marketplace-app-ktor/src/commonMain/kotlin/MkplAppSettings.kt
> +fun getAppSettingsWithRepo(repo: IAdRepository): MkplAppSettings {
этот метод отсюда нужно убрать.
1. Он исключительно для обслуживания тестов, в боевой инфраструктуре не используется.
2. Он совершенно не расширяемый. Что будем делать, когда тестовых параметров накопится с десяток?

2023-04-23 15:34 UTC, svok commented on ok-marketplace-app-ktor/src/commonMain/kotlin/plugins/InitAppSettings.kt
> +        repoTest = AdRepoInMemory()
Куда делись repoStub, repoProd?

2023-04-23 15:34 UTC, svok commented on ok-marketplace-app-ktor/src/commonMain/kotlin/v2/ControllerHelperV2.kt
> +        settings = appSettings.corSettings,
Этого не должно быть здесь. Это делается в процессоре

2023-04-23 15:34 UTC, svok commented on ok-marketplace-app-ktor/src/commonTest/kotlin/ru/otus/otuskotlin/marketplace/app/ktor/repo/V2AdInmemoryApiTest.kt
> +            module(getAppSettingsWithRepo(repo))
Давай просто сделаем как было в 202206

2023-04-23 15:34 UTC, svok commented on ok-marketplace-app-ktor/src/commonTest/kotlin/ru/otus/otuskotlin/marketplace/app/ktor/repo/V2AdInmemoryApiTest.kt
> +            appUrls = emptyList(),
1. Весь этот метод - дубль.
2. Ради appUrls не стоило создавать отдельный метод. Достаточно было задать значение по умолчанию. Именно так и было сделано в предыдущий раз.

2023-04-23 15:34 UTC, svok commented on ok-marketplace-app-ktor/src/jvmMain/kotlin/v1/ControllerHelperV1.kt
> +        settings = appSettings.corSettings,
Это не должно быть здесь

2023-04-23 15:34 UTC, svok commented on ok-marketplace-app-ktor/src/jvmTest/kotlin/ru/otus/otuskotlin/marketplace/app/ktor/repo/V1AdMockApiTest.kt
> +            val repo by lazy {
lazy в этом месте совершенно неоправдан. Это если бы он был в теле класса, тогда был бы резон. Но здесь он внутри функции, которая его использует

2023-04-23 15:34 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/common/WorkModeExt.kt
> +fun MkplContext.withWorkModeBasedOnSettings(corSettings: MkplCorSettings): MkplContext {
Ничего подобного. Нельзя так делать. Удали его

2023-04-23 15:34 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/service/MkplAdBlockingProcessor.kt
> +class MkplAdBlockingProcessor(private val mkplCorSettings: MkplCorSettings) {
Этот класс нужно полностью удалить

2023-04-23 15:34 UTC, svok commented on ok-marketplace-app-spring/src/test/kotlin/ru/otus/otuskotlin/markeplace/springapp/config/TestConfig.kt
> +        repoTest = AdRepoInMemory()
И как сюда стартовые объекты проталкивать?

2023-04-23 15:34 UTC, svok commented on ok-marketplace-app-spring/src/test/kotlin/ru/otus/otuskotlin/markeplace/springapp/config/TestConfig.kt
> +        repoTest = AdRepoInMemory()
Не было на прошлых занятиях такого

2023-04-23 15:34 UTC, svok commented on ok-marketplace-biz/src/commonMain/kotlin/ru/otus/otuskotlin/marketplace/biz/repo/AdRepoOffers.kt
> +    handle {
CoR - это управляющий шаблон. Если обработчик разрастается, значит что-то нужно делать: либо разбивать на несколько обработчиков, либо выносить отдельные классы.

2023-04-23 15:34 UTC, svok commented on ok-marketplace-biz/src/commonTest/kotlin/ru/otus/otuskotlin/marketplace/biz/validation/ValidationBadTitle.kt
Не надо делать эти переносы. 
Ничего удобного в сотнях пустых директорий нет.

2023-04-23 15:34 UTC, svok commented on ok-marketplace-common/src/commonMain/kotlin/models/MkplAd.kt
> +        val NONE get() = MkplAd()
```suggestion
        private val NONE = MkplAd()
```
это же для сравнения. Его нужно отдельным методом делать. Незачем плодить пустые объекты

2023-04-23 15:34 UTC, svok commented on ok-marketplace-repo-stubs/README.MD
> +# Модуль `ok-marketplace-repo-in-memory`
stub не имеет отношения к in-memory

2023-04-23 15:34 UTC, svok commented on ok-marketplace-repo-tests/src/commonMain/kotlin/RepoAdDeleteTest.kt
> +        assertEquals("lock", error?.field)
это точно работает? просто блокировки не след. занятии только появятся

2023-04-23 16:07 UTC, tano commented on ok-marketplace-app-ktor/src/commonMain/kotlin/MkplAppSettings.kt
> +fun getAppSettingsWithRepo(repo: IAdRepository): MkplAppSettings {
Есть один момент: в прошлом модуле у нас был один класс для настроек - MkplSettings, сейчас есть MkplAppSettings, который включает MkplCorSettings. Прежде чем от него избавляться, нужно определиться, как мы работаем с настройками.

Предлагаю учесть следующее:
1) Вы в MkplContext добавили в прошлых занятиях свойство settings с типом MkplCorSettings, поля которого используются в DSL функция initRepo.
2) При этом в функцию расширения moduleJvm передаётся параметр типа MkplAppSettings 

Т.е. нам придётся в каждом тесте городить довольно большую конструкцию с созданием иерархии настроек, на мой взгляд, лучше корявый метод, чем такая копипаста. 

С чем согласен, так с это с тем, что его лучше бы перенести в тестовый код, это можно сделать.

2023-04-23 16:11 UTC, tano commented on ok-marketplace-app-ktor/src/commonMain/kotlin/plugins/InitAppSettings.kt
> +        repoTest = AdRepoInMemory()
Что мы можем здесь присвоить в repoStub, repoProd? 
В прошлом потоке у нас не было такой абстракции, была функция Application.module, в ней были настройки вот такие:

`val corSettings by lazy {
        settings ?: MkplSettings(
            repoTest = AdRepoInMemory()
        )
    }`

2023-04-23 16:17 UTC, tano commented on ok-marketplace-app-ktor/src/commonMain/kotlin/v2/ControllerHelperV2.kt
> +        settings = appSettings.corSettings,
Да,  так и сделал первоначально, но в таком случае у нас случится ошибка в ICorChainDsl<MkplContext>.initRepo по ветке 
`if (workMode != MkplWorkMode.STUB && adRepo == IAdRepository.NONE) fail(
            errorAdministration(
                field = "repo",
                violationCode = "dbNotConfigured",
                description = "The database is unconfigured for chosen workmode ($workMode). " +
                        "Please, contact the administrator staff"
            )
        )`

2023-04-23 16:20 UTC, tano commented on ok-marketplace-app-ktor/src/commonTest/kotlin/ru/otus/otuskotlin/marketplace/app/ktor/repo/V2AdInmemoryApiTest.kt
> +            module(getAppSettingsWithRepo(repo))
Я так и хотел, выше (в комментарии про getAppSettingsWithRepo) написал, почему от этого ушёл.

2023-04-23 16:22 UTC, tano commented on ok-marketplace-app-ktor/src/commonTest/kotlin/ru/otus/otuskotlin/marketplace/app/ktor/repo/V2AdInmemoryApiTest.kt
> +            appUrls = emptyList(),
В прошлый раз имеется в виду прошлый поток? Если так, то там не было appUrls. Или что-то другое имеется виду.

2023-04-23 16:22 UTC, tano commented on ok-marketplace-app-ktor/src/jvmMain/kotlin/v1/ControllerHelperV1.kt
> +        settings = appSettings.corSettings,
Могу то же ответить, что и в комментарии про [ControllerHelperV2.kt](https://github.com/otuskotlin/202212-ok-marketplace/pull/27/files/0ef4a6163ffc26b3f00f72a324e572ff6acd4665#diff-e27af6723fb1bec5daf7e9d16db995c6b6a454b19a23273a356582507a3f4509)

2023-04-23 16:25 UTC, tano commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/common/WorkModeExt.kt
> +fun MkplContext.withWorkModeBasedOnSettings(corSettings: MkplCorSettings): MkplContext {
Сергей, я бы рад его удалить, но тогда сломаются интеграционные тесты WebSocket с руганью о том, что не настроена база данных.

2023-04-23 16:25 UTC, tano commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/service/MkplAdBlockingProcessor.kt
> +class MkplAdBlockingProcessor(private val mkplCorSettings: MkplCorSettings) {
Этот класс был создан не мной, а Евгением на занятии по Spring. Что предлагается вместо него?

2023-04-23 16:27 UTC, tano commented on ok-marketplace-app-spring/src/test/kotlin/ru/otus/otuskotlin/markeplace/springapp/config/TestConfig.kt
> +        repoTest = AdRepoInMemory()
Действительно, такого не было, потому что не было и бинов для процессоров, а также WsAdHandlerV2 был другой. Я исходил из того, что эти изменения нужно оставить.

2023-04-23 16:30 UTC, tano commented on ok-marketplace-biz/src/commonMain/kotlin/ru/otus/otuskotlin/marketplace/biz/repo/AdRepoOffers.kt
> +    handle {
В предыдущих пунктах Вы давали ссылку на прошлые лекции, здесь я как раз попытался сохранить преемственность. Пока не вижу критики в разрастании.

2023-04-23 16:31 UTC, tano commented on ok-marketplace-repo-tests/src/commonMain/kotlin/RepoAdDeleteTest.kt
> +        assertEquals("lock", error?.field)
Убрал уже

2023-04-23 16:34 UTC, tano commented on ok-marketplace-biz/src/commonTest/kotlin/ru/otus/otuskotlin/marketplace/biz/validation/ValidationBadTitle.kt
Ок перенесу обратно.

2023-04-23 16:36 UTC, tano commented on README.md
> +[//]: # (2. [ok-marketplace-repo-in-memory]&#40;ok-marketplace-repo-in-memory&#41; - Репозиторий на базе кэша в памяти для тестирования)
Сделал.

2023-04-23 16:36 UTC, tano commented on ok-marketplace-app-ktor/src/jvmTest/kotlin/ru/otus/otuskotlin/marketplace/app/ktor/repo/V1AdMockApiTest.kt
> +            val repo by lazy {
Убрал.

2023-04-23 18:29 UTC, tano commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/common/WorkModeExt.kt
> +fun MkplContext.withWorkModeBasedOnSettings(corSettings: MkplCorSettings): MkplContext {
Разобрались, удалил.

2023-04-23 18:29 UTC, tano commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/service/MkplAdBlockingProcessor.kt
> +class MkplAdBlockingProcessor(private val mkplCorSettings: MkplCorSettings) {
Разобрались, удалил.

2023-04-23 18:35 UTC, tano commented on ok-marketplace-app-spring/src/test/kotlin/ru/otus/otuskotlin/markeplace/springapp/config/TestConfig.kt
> +        repoTest = AdRepoInMemory()
Разобрались, удалил.

2023-04-23 18:47 UTC, tano commented on ok-marketplace-app-ktor/src/commonTest/kotlin/ru/otus/otuskotlin/marketplace/app/ktor/repo/V2AdInmemoryApiTest.kt
> +            module(getAppSettingsWithRepo(repo))
Разобрбались, убрал.

2023-04-23 18:51 UTC, tano commented on ok-marketplace-app-ktor/src/commonMain/kotlin/MkplAppSettings.kt
> +fun getAppSettingsWithRepo(repo: IAdRepository): MkplAppSettings {
Разобрались, удалил.

2023-04-23 19:02 UTC, tano commented on ok-marketplace-app-ktor/src/commonMain/kotlin/plugins/InitAppSettings.kt
> +        repoTest = AdRepoInMemory()
Разобрались, добавил.

2023-04-23 19:08 UTC, tano commented on ok-marketplace-app-ktor/src/commonMain/kotlin/v2/ControllerHelperV2.kt
> +        settings = appSettings.corSettings,
Разобрались, убрал.

2023-04-23 19:09 UTC, tano commented on ok-marketplace-app-ktor/src/commonTest/kotlin/ru/otus/otuskotlin/marketplace/app/ktor/repo/V2AdInmemoryApiTest.kt
> +            appUrls = emptyList(),
Разобрался, убрал.

2023-04-23 19:12 UTC, tano commented on ok-marketplace-app-ktor/src/jvmMain/kotlin/v1/ControllerHelperV1.kt
> +        settings = appSettings.corSettings,
Разобрался, удалил.

2023-04-23 19:13 UTC, tano commented
Так, всё поправил, кроме [AdRepoOffers.kt](https://github.com/otuskotlin/202212-ok-marketplace/pull/27/files/0ef4a6163ffc26b3f00f72a324e572ff6acd4665#diff-9f784a131c28159f8e2e2c71323ee7d7140408310bfe0da162e72e33599dbd74), кажется, там пока не так критично разросся он..

2023-04-23 19:20 UTC, tano commented
@svok, просьба посмотреть правки.

2023-04-24 05:33 UTC, svok requested changes
Отлично. Есть еще несколько мелочей. Их поправить и будет совсем нормально.

2023-04-24 05:33 UTC, svok commented on ok-marketplace-app-ktor/src/commonMain/kotlin/v2/ControllerHelperV2.kt
> +        settings = appSettings.corSettings,
```suggestion
```

2023-04-24 05:33 UTC, svok commented on ok-marketplace-app-ktor/src/commonMain/kotlin/plugins/InitAppSettings.kt
>      processor = MkplAdProcessor(),
```suggestion
    processor = MkplAdProcessor(corSettings),
```

2023-04-24 05:33 UTC, svok commented on ok-marketplace-app-ktor/src/commonMain/kotlin/plugins/InitAppSettings.kt
> +        repoTest = AdRepoStub(),
```suggestion
        repoTest = AdRepoInMemory(),
```

2023-04-24 05:33 UTC, svok commented on ok-marketplace-biz/src/commonTest/kotlin/repo/BizRepoDeleteTest.kt
> +package repo
Поправь пакет

2023-04-24 05:33 UTC, svok commented on ok-marketplace-biz/src/commonTest/kotlin/repo/BizRepoDeleteTest.kt
> +package repo
```suggestion
package ru.otus.otuskotlin.marketplace.biz.repo
```

2023-04-24 05:33 UTC, svok commented on ok-marketplace-biz/src/commonTest/kotlin/repo/RepoByIdTests.kt
> +    get() = AdRepositoryMock(
Тут точно нужен геттер? Зачем каждый раз создавать новый инстанс?

2023-04-24 05:33 UTC, svok commented on ok-marketplace-biz/src/commonTest/kotlin/validation/ValidationBadTitle.kt
> +package validation
Это зачем так исправил? Нет. Надо вернуть

2023-04-24 05:33 UTC, svok commented on ok-marketplace-common/src/commonMain/kotlin/models/MkplAd.kt
> +        private val NONE = MkplAd()
Раз уж он в сравнении используется, то тогда нужно предоставить функцию сравнения
```kotlin
    fun isEmpty() = this == NONE
```

2023-04-24 05:33 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/config/CorConfig.kt
> +    fun testRepository() = AdRepoStub()
```suggestion
    fun testRepository() = AdRepoInMemory()
```

2023-04-24 05:57 UTC, tano commented on ok-marketplace-biz/src/commonTest/kotlin/validation/ValidationBadTitle.kt
> +package validation
А тут вот какая штука происходит: IDEA ругается "Package directive does not match the file location", тесты не запустит в этом пакете. Я поэтому и создавал первоначально тот набор директорий пустой.

2023-04-24 06:02 UTC, tano commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/config/CorConfig.kt
> +    fun testRepository() = AdRepoStub()
Поправил.

2023-04-24 06:03 UTC, tano commented on ok-marketplace-biz/src/commonTest/kotlin/repo/RepoByIdTests.kt
> +    get() = AdRepositoryMock(
Согласен, поправил.

2023-04-24 06:11 UTC, tano commented on ok-marketplace-biz/src/commonTest/kotlin/repo/BizRepoDeleteTest.kt
> +package repo
Поправил, для единообразия с другими тестами можно оставить, но мне кажется на будущее, что не очень хорошо вот эту проблему себе создавать "Package directive does not match the file location", из-за неё какие-нибудь тулы вроде идеи могут тесты проигнорировать, Спринг из-за подобного вообще с ума сходит..

2023-04-24 06:11 UTC, tano commented on ok-marketplace-biz/src/commonTest/kotlin/validation/ValidationBadTitle.kt
> +package validation
https://github.com/otuskotlin/202212-ok-marketplace/pull/27#discussion_r1174826347

2023-04-24 06:17 UTC, tano commented
Исправил, по пакетам можно пока так оставить, но мне кажется, далее лучше всё же соблюдать соответствие пакетов и структуры каталогов исходя из того, что какой-нибудь тул может на это некорректно среагировать.

2023-04-24 06:23 UTC, tano commented
@svok, я вот о чем (про пакеты): https://github.com/otuskotlin/202212-ok-marketplace/pull/27#discussion_r1174826347

2023-04-24 18:17 UTC, svok commented on ok-marketplace-biz/src/commonTest/kotlin/repo/BizRepoDeleteTest.kt
> +package repo
Так в чем проблема? Поправь так, чтоб матчил. Эти ошибки вылазят, если у тебя в одной директории разные пакаджи. Поставь все пакаджи одинаковые и все ему понравится. И в поддиректориях должно все соответствовать тому, что в руте подпроекта.

2023-04-24 18:35 UTC, svok approved these changes

2023-04-24 18:35 UTC, svok commented on ok-marketplace-biz/src/commonMain/kotlin/ru/otus/otuskotlin/marketplace/biz/repo/AdRepoCreate.kt
> +package ru.otus.otuskotlin.marketplace.biz.repo
Еще раз. Директории убери, а пакет оставь.

-biz/src/commonMain/kotlin/ru/otus/otuskotlin/marketplace/biz/repo/AdRepoCreate.kt -> -biz/src/commonMain/kotlin/AdRepoCreate.kt

2023-04-24 18:35 UTC, svok commented on ok-marketplace-biz/src/commonMain/kotlin/ru/otus/otuskotlin/marketplace/biz/repo/AdRepoCreate.kt
> +package ru.otus.otuskotlin.marketplace.biz.repo
Ладно, я понял. Это какой-то злодей среди нас завелся и сделал структуру каталогов в джавовом стиле. 
Хоршо, я не буду тебя заставлять во всем модуле бизнес-логики менять структуру файлов

2023-04-24 18:35 UTC, svok commented on ok-marketplace-biz/src/commonTest/kotlin/repo/RepoByIdTests.kt
> +package repo
Вот опять косячный пакет. Проверь по всему коду

2023-04-29 09:29 UTC, merged