M5l3
otuskotlin/202212-ok-marketplace pull request #29
Opened 2023-05-04 21:50 UTC by evgnep

2023-05-05 13:03 UTC, svok requested changes

2023-05-05 13:03 UTC, svok commented on ok-marketplace-app-spring/Dockerfile
> +COPY build/libs/ok-marketplace-app-spring-0.0.3.jar /app/app.jar
Это для чего здесь вообще этот файл? Тем более в таком трэшевом виде

2023-05-05 13:03 UTC, svok commented on ok-marketplace-repo-postgresql/src/main/kotlin/ru/otus/otuskotlin/marketplace/backend/repo/sql/RepoAdSQL.kt
> +    schema: String = System.getenv("JDBC_SCHEMA") ?: "marketplace",
Все без исключения `System.getenv` нужно убрать. Работа со средой должна присутствовать ТОЛЬКО в фреймворке. Более того, во фреймворке вообще-то отедельный файл настроек присутствует.
И вообще, в проекте есть стиль, согласно которому есть Separation of Concerns. Нельзя смешивать работу с БД и чтение настроек из каких-то сред.

2023-05-05 13:03 UTC, svok commented on ok-marketplace-repo-postgresql/src/main/kotlin/ru/otus/otuskotlin/marketplace/backend/repo/sql/RepoAdSQL.kt
> +            val result = (AdsTable innerJoin UsersTable).select { AdsTable.id.eq(rq.id.asString()) }.single()
Зачем нам здесь UsersTable? Ее вечно Кирилл вставляет, непонятно зачем

2023-05-05 13:03 UTC, svok commented on ok-marketplace-repo-postgresql/src/main/kotlin/ru/otus/otuskotlin/marketplace/backend/repo/sql/RepoAdSQL.kt
> +            } ?: return@safeTransaction resultErrorNotFound
Не самое эффективное решение. 
Вот здесь одним запросом вопрос решают
https://stackoverflow.com/a/37813771

2023-05-05 13:03 UTC, svok commented on ok-marketplace-repo-postgresql/src/main/kotlin/ru/otus/otuskotlin/marketplace/backend/repo/sql/SqlConnector.kt
> +class SqlConnector(
От этого класса тоже можно смело избавляться. Тоже наследие Кирилла. Никак не могу заставить его убрать лишний код, только запутывающий студентов.
MySQL у нас на курсе точно не используется. Зачем это усложнение, мне не ясно.

2023-05-05 13:03 UTC, svok commented on ok-marketplace-repo-postgresql/src/main/kotlin/ru/otus/otuskotlin/marketplace/backend/repo/sql/SqlConnector.kt
> +class SqlConnector(
Явное нарушение YAGNI

2023-05-05 13:03 UTC, svok commented on ok-marketplace-repo-postgresql/src/main/kotlin/ru/otus/otuskotlin/marketplace/backend/repo/sql/SqlConnector.kt
> +                    connection.prepareStatement("CREATE SCHEMA IF NOT EXISTS $schema", false).executeUpdate()
Для этого миграции существуют. Лучше о них обмолвиться вкратце, чем вот такое безобразие делать.

2023-05-05 13:03 UTC, svok commented on ok-marketplace-repo-postgresql/src/main/kotlin/ru/otus/otuskotlin/marketplace/backend/repo/sql/SqlConnector.kt
> +            if (System.getenv("ok.mp.sql_drop_db")?.toBoolean() == true) {
Охренеть, в репозитории getenv

2023-05-05 13:33 UTC, evgnep commented on ok-marketplace-app-spring/Dockerfile
> +COPY build/libs/ok-marketplace-app-spring-0.0.3.jar /app/app.jar
для сборки докера. В спринге есть сборка из коробки, но не как-то переусложненно. Могу бмушко подключить

2023-05-05 13:34 UTC, evgnep commented on ok-marketplace-repo-postgresql/src/main/kotlin/ru/otus/otuskotlin/marketplace/backend/repo/sql/RepoAdSQL.kt
> +    schema: String = System.getenv("JDBC_SCHEMA") ?: "marketplace",
у нас в кафке была работа с переменными среды. Ну можно и убрать....

2023-05-05 13:35 UTC, evgnep commented on ok-marketplace-repo-postgresql/src/main/kotlin/ru/otus/otuskotlin/marketplace/backend/repo/sql/RepoAdSQL.kt
> +            val result = (AdsTable innerJoin UsersTable).select { AdsTable.id.eq(rq.id.asString()) }.single()
без понятия :) Видимо для демонстрации join

2023-05-05 13:37 UTC, evgnep commented on ok-marketplace-repo-postgresql/src/main/kotlin/ru/otus/otuskotlin/marketplace/backend/repo/sql/SqlConnector.kt
> +                    connection.prepareStatement("CREATE SCHEMA IF NOT EXISTS $schema", false).executeUpdate()
так а что ты предлагаешь - ликвибейз тут накручивать? А БД нам надо таки создавать... Не руками же запрос делать....

2023-05-05 13:37 UTC, evgnep commented on ok-marketplace-repo-postgresql/src/main/kotlin/ru/otus/otuskotlin/marketplace/backend/repo/sql/SqlConnector.kt
> +class SqlConnector(
ну можно и убрать мускул... А можно и нет, просто для демонстрации того, как действовать для разных БД

2023-05-05 16:10 UTC, evgnep commented on ok-marketplace-repo-postgresql/src/main/kotlin/ru/otus/otuskotlin/marketplace/backend/repo/sql/RepoAdSQL.kt
> +            } ?: return@safeTransaction resultErrorNotFound
там решают без exposed. Я не знаю, как сделать with c exposed + у нас тут вторая таблица имеет место быть

2023-05-07 21:05 UTC, svok commented on ok-marketplace-app-spring/Dockerfile
> +COPY build/libs/ok-marketplace-app-spring-0.0.3.jar /app/app.jar
О чем ты?
```bash
./gradlew bootBuildImage --imageName=myorg/myapp
```

2023-05-08 06:40 UTC, svok approved these changes

2023-05-08 06:41 UTC, merged